### ISSUE TITLE
No redirect_to field in types.AuthorizeRequest

### ISSUE THREAD

**Issue by daic0r** [supabase-community/auth-go#4]
# Bug report

## Describe the bug

With Supabase's `/auth/v1/authorize` endpoint it is possible to pass a callback URL in the field `redirect_to`.
This is required in order to pass in a custom endpoint which will handle the code exchange in a PKCE flow.

See the description on [Login with Github](https://supabase.com/docs/guides/auth/social-login/auth-github?queryGroups=environment&environment=server&queryGroups=framework&framework=express#add-login-code-to-your-client-app).

Without this, the redirect seems to go to `/`.

Currently, it is not possible to pass such a URL to `Authorize`.

## To Reproduce

1. Initiate a flow with a call to `Client.Authorize`
2. Redirect to the URL returned by it
3. Supabase will redirect to `/`, passing the code as a URL parameter.

## Expected behavior

`AuthorizeRequest` should have an additional field `RedirectTo string` which will then be used inside `Authorize`.
Step 3 above would then redirect to this URL.

## Additional context

I tried this with the GitHub provider.

**Comment by kwoodhouse93** [comment]
Addressed by #7
